runtime: python
env: flex
runtime_config:
  python_version: 3
# entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker sone.api:app
entrypoint: uvicorn sone.api:app --host 0.0.0.0 --port $PORT
network:
  session_affinity: true
manual_scaling:
  instances: 1
